### ISSUE TITLE
Perform tests with multi-dimensional action space

### ISSUE THREAD

**Issue by javiarrobas** [ibpsa/project1-boptest-gym#19]
So far all tests are performed with a one-dimensional action space. Potential issues may arise from the implementation of the interface with a multi-dimensional action space. It'd be convenient to perform tests in a multi-dimensional action space to prevent those issues.

**Comment by IamAniket12** [comment]
Hi @javiarrobas, I tried it with multi-action, but it didn't work. If it’s not assigned to anyone yet, I’d be interested in taking it on.

**Comment by javiarrobas** [comment]
This is of high priority. Please send a pull request if you get it to work and I'll review it.

**Comment by IamAniket12** [comment]
Done!! Create a pull request please review it.
