### ISSUE TITLE
Start time argument

### ISSUE THREAD

**Issue by javiarrobas** [ibpsa/project1-boptest-gym#46]
Right now two separate arguments are being used to define the starting time of an episode: `random_start_time` and `start_time`, with the latter being used when `random_start_time=False`. It'd be clearer and cleaner to use only one argument: `start_time` that can have either a fixed value or be assigned `None` in which case a random time is used.

**Comment by IamAniket12** [comment]
Hello @javiarrobas, if this issue has not yet been assigned to someone else, I would be pleased to take on the this task.

**Comment by javiarrobas** [comment]
@IamAniket12 it'd be great if you could take it up. If you do so please send a pull request against master once ready. I'll be happy to review it.

**Comment by IamAniket12** [comment]
Done!! Created a pull request please review it
